# @package _global_
prop_model_cov:
  n_estimators: 100
  max_depth: 6
  reg_alpha: 80
  min_child_weight: 0
  gamma: 9

mu_model_cov:
  n_estimators: 100
  max_depth: 12
  reg_alpha: 120
  min_child_weight: 3
  gamma: 1
  mu_model_type: t

dataset:
  n_samples_train: 500
