# @package _global_
dataset:
  _target_: src.data.ACIC2016
  name: acic2016
  collection: True
  train_test_splitted: False
  oracle_available: True
  test_size: 0.15
  n_shuffle_splits:  5           # not applicable
  extra_hid_multiplier: 0.25

  dim_cov: 82

exp:
  save_results: False